# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llikWeibull <- function(Y, eXB, alpha, C, lambda) {
    .Call('_BayesMFsurv_llikWeibull', PACKAGE = 'BayesMFsurv', Y, eXB, alpha, C, lambda)
}

llikWeibull2 <- function(Y, eXB, alpha, C, lambda) {
    .Call('_BayesMFsurv_llikWeibull2', PACKAGE = 'BayesMFsurv', Y, eXB, alpha, C, lambda)
}

