# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llikWeibull_betas <- function(Y, eXB, alpha, C, lambda) {
    .Call('BayesOFsurv_llikWeibull_betas', PACKAGE = 'BayesOFsurv', Y, eXB, alpha, C, lambda)
}

llikWeibull_gammas <- function(Y, eXB, Z, gammas, C, lambda) {
    .Call('BayesOFsurv_llikWeibull_gammas', PACKAGE = 'BayesOFsurv', Y, eXB, Z, gammas, C, lambda)
}

llikWeibull_lambda <- function(Y, eXB, alpha, C, lambda) {
    .Call('BayesOFsurv_llikWeibull_lambda', PACKAGE = 'BayesOFsurv', Y, eXB, alpha, C, lambda)
}

llikWeibull_betas2 <- function(Y, eXB, alpha, C, lambda) {
    .Call('BayesOFsurv_llikWeibull_betas2', PACKAGE = 'BayesOFsurv', Y, eXB, alpha, C, lambda)
}

llikWeibull_gammas2 <- function(Y, eXB, Z, gammas, C, lambda) {
    .Call('BayesOFsurv_llikWeibull_gammas2', PACKAGE = 'BayesOFsurv', Y, eXB, Z, gammas, C, lambda)
}

llikWeibull_lambda2 <- function(Y, eXB, alpha, C, lambda) {
    .Call('BayesOFsurv_llikWeibull_lambda2', PACKAGE = 'BayesOFsurv', Y, eXB, alpha, C, lambda)
}

