// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// llikWeibull
double llikWeibull(arma::vec Y, arma::mat X, arma::vec betas, arma::mat Z, arma::vec gammas, arma::vec C, double lambda);
RcppExport SEXP BayesOFsurv_llikWeibull(SEXP YSEXP, SEXP XSEXP, SEXP betasSEXP, SEXP ZSEXP, SEXP gammasSEXP, SEXP CSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gammas(gammasSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikWeibull(Y, X, betas, Z, gammas, C, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"BayesOFsurv_llikWeibull", (DL_FUNC) &BayesOFsurv_llikWeibull, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesOFsurv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
